version: '3.5'
services:
  srtla-nginx:
    image: ${REPOSITORY_NAME}/${PROJECT_NAME}-srtla-nginx:${GLOBAL_VERSION}
    container_name: srtla-nginx
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports: 
      - "30000:30000/udp"
      - "8282:8181/tcp"
    volumes:
      - ./sls.conf:/etc/sls/sls.conf
  srtla-receiver:
    image: ${REPOSITORY_NAME}/${PROJECT_NAME}-srtla-receiver:${GLOBAL_VERSION}
    container_name: srtla-receiver
    restart: unless-stopped
    ports:
      - "5000:5000/udp"
      - "5001:5001/udp"
    volumes:
      - ./entrypoint.sh:/tmp/entrypoint.sh
    environment:
      - SRT_ENDPOINT_ADDR=belabox-srtla-nginx
      - SRT_ENDPOINT_PORT=30000
    depends_on:
      - "srtla-nginx"
